### PR TITLE
safely handle "@" in usernames

### PR DESCRIPTION
**Pull request by garnertb**
Prevent "@" from breaking this.

### CODE REVIEW

**Review by lindluni — APPROVED** [review]
Approving and merging, but can we change the license in package.json and not package-lock.json, package-lock is generated from a package.json

**Comment by garnertb** [comment]
Yah, I didn't know why the license change showed up but assumed you changed it and forgot run update package-lock...

**Comment by garnertb** [comment]
Confirming this is what happened, you added it here: https://github.com/lindluni/warden-status/commit/4c27088815b3752222c7cfd799da6e6b78c3bd3d.

**Comment by lindluni** [comment]
Ahhh, I updated it in package.json, but didn't run npm install because depa didn't change. Good catch!!!!

**Pull request merged**
